# Generated by Django 4.0.5 on 2022-06-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_sheet', models.IntegerField(verbose_name='№')),
                ('number_of_order', models.IntegerField(verbose_name='заказ №')),
                ('price_usd', models.FloatField(verbose_name='стоимость,$')),
                ('delivery_time', models.DateTimeField(verbose_name='срок поставки')),
                ('price_rub', models.FloatField(verbose_name='стоимость в руб.')),
            ],
        ),
    ]
